# DS-GA 1019

# Lecture 3 - The itertools Module
## Feb. 4, 2026

# Today

- The concept of iterators
- Infinite Iterators
- Finite Iterators
- Combinatoric Generators

## Arrays/lists vs iterators

- When creating an array (as well as a list or tuple), we first have to allocate a block of system memory to store these elments.  


- When we only need to iterate through a list, there might be no need to store it


- The _itertools_ module implements a number of iterator building blocks that provide a set of fast, memory efficient tools.

- Iterator-based code may be preferred over code which uses lists for several reasons.

-  Since data is not produced from the iterator until it is needed, all of the data is not stored in memory at the same time.
- Reducing memory usage can reduce swapping and other side-effects of large data sets, increasing performance.


---

The __itertools__ module implements a number of iterator building blocks that provide fast, memory efficient tools.

These building blocks can be used to form an “iterator algebra” making it possible to construct specialized tools succinctly and efficiently in pure Python.

A generator behaves like a list of values, with some **important differences**:

- The values are generated on demand (sequence is not stored in memory)
- The values can only be accessed in sequence (not like an array)
- The values can only be accessed once



What is an iterator? An iterator is an object that provides two methods:

-  __ iter __  which returns the iterator itself
-  __ next __ which returns the next value from the iterator



In [4]:
it = iter('advanced_python')

# first 7 elements

print(it.__next__())
print(it.__next__())
print(it.__next__())
print(it.__next__())
print(it.__next__())
print(it.__next__())
print(next(it))

a
d
v
a
n
c
e


In [5]:
# the rest
lst = [e for e in it]
print("\nlst: %s" % lst)


lst: ['d', '_', 'p', 'y', 't', 'h', 'o', 'n']


- Finally the program generates a StopIteration exception because an attempt is made to access a completed iterator.

In [6]:
# at this point the iterator is completed

print(it.__next__())

StopIteration: 

In [7]:
it = iter('advanced_python')
print(list(it))


['a', 'd', 'v', 'a', 'n', 'c', 'e', 'd', '_', 'p', 'y', 't', 'h', 'o', 'n']


In [8]:
# At this point the iterator is finished
print(list(it))

[]


In [9]:
# enumerate() method adds a counter to an iterable
it = iter('advanced_python')

#print(it.__next__())

for i, elem in enumerate(it):
    print(i, elem)


0 a
1 d
2 v
3 a
4 n
5 c
6 e
7 d
8 _
9 p
10 y
11 t
12 h
13 o
14 n


In [10]:
# Additionally look at:
for i in range(10):
    print(i)
    # some_work(i)

0
1
2
3
4
5
6
7
8
9


---

### range() vs xrange()

#### In Python2: 

- range(): returns a list  
- xrange(): returns a generator object
    
#### In Python3: 
- there is no xrange, and range returns a ~~generator~~ (technically, it's not a generator; it's a range object)
- `range` is an **immutable sequence type** that behaves like a generator (memory-efficient), but iterable

A difference between generator and iterator:
- **iterator** is the object that has `__iter__()` and `__next__()` magic methods, and raises `StopIteration` exception when done.
- **generator** is created using `yield` keyword; Python automatically/internally builds the iteartor logic.

In [18]:
# range: returns a list
def demo_range(start, stop, step=1):
    numbers = []
    while start < stop:
        numbers.append(start)
        start += step
    return numbers

---

- Note that the range implementation must create/allocate the list of all numbers within the range.

- We use memory for "all numbers".


In [19]:
# xrange: returns a generator

def demo_xrange(start, stop, step=1):
    while start < stop:
        yield start
        start += step

# We do not precreate the list of all numbers within the range.

# We do not use memory for "all numbers".


----

- The generator is able to 'return' many values. 

- Every time the code gets to the yield, the function produces its value

- when another value is requested the function resumes running (maintaining its previous state) and produces the new value.
  ```python
    def f():
        print("A")
        yield 1
        print("B")
        yield 2

        
    g = f()        # nothing runs yet

    a = next(g)        # prints "A", returns 1, variable 'a' is 1
                       # pauses at first yield

    b = next(g)        # resumes after first yield
                       # prints "B", returns 2, variable 'b' is 2
  ```

In [24]:
# how many numbers in list_of_numbers are divisible by 3?

list_of_numbers = demo_range(0, 1000)
divisible_by_three = len([n for n in list_of_numbers if n % 3 == 0])

print("divisible_by_three:", divisible_by_three)

divisible_by_three: 334


## List vs generator comprehensions

List:

```[ <value> for <item> in <sequence> if <condition> ]```

Generator:

```( <value> for <item> in <sequence> if <condition> )```

In [16]:
yy = (i for i in list(range(10)))
print(type(yy))
print(yy.__next__())
#print(yy.__next__())
#print(yy.__next__())

<class 'generator'>
0


In [12]:
[i for i in list(range(10))]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
#Here, we have a generator that produce a value of 1 whenever it encounters a number divisible by 3,
# and nothing otherwise.

list_of_numbers = demo_xrange(0, 1000)
generator = (1 for n in list_of_numbers if n % 3 == 0)
print("generator:", generator)
divisible_by_three = sum(generator)
print(divisible_by_three)


generator: <generator object <genexpr> at 0x107c65c10>
334


In [22]:
# at this point, generator is completed

for e in generator:
    print(e)

print('checking: ', sum(generator))

checking:  0


## Infinite Iterators
__itertools__ package comes with three iterators that can iterate infinitely.
- useful for generating numbers or cycling over iterables of unknown length
- infinite iterators need to be stopped

#### itertools.count(start,step)  

- Make an iterator that returns evenly spaced values starting with number start

https://docs.python.org/3/library/itertools.html#itertools.count

In [ ]:
from itertools import count

for i in count(10, 3):
    print(i)
    if i >= 30: break


10
13
16
19
22
25
28
31


#### itertools.islice(seq, [start,] stop [, step])   

https://docs.python.org/3/library/itertools.html#itertools.islice

Make an iterator that returns selected elements from the iterable. **This is analogous to the list slicing, but for the iterator.**

In [ ]:
from itertools import islice

print(list(islice(count(10, 3), 5)))     # first 5 elements
print(list(islice(count(10, 3), 10)))    # first 10 elements
print(list(islice(count(10, 3), 5, 10))) # second 5 elements: from 5th to 9th element included

[10, 13, 16, 19, 22]
[10, 13, 16, 19, 22, 25, 28, 31, 34, 37]
[25, 28, 31, 34, 37]


In [ ]:
# itertools.islice(seq, [start,] stop [,step])

# first 10 elements
print(list(islice(count(10, 3), 10)))

# from 3rd to 9th element (including those), every second element
print(list(islice(count(10, 3), 3, 10, 2)))

[10, 13, 16, 19, 22, 25, 28, 31, 34, 37]
[19, 25, 31, 37]


**None**: "If stop is None, then iteration continues until the iterator is exhausted, if at all; otherwise, it stops at the specified position."

In [31]:
print(list(islice('ABCDEFG', 2, None)))
print(list(islice('ABCDEFG', 100))) # and len('ABCDEFG') = 7

['C', 'D', 'E', 'F', 'G']
['A', 'B', 'C', 'D', 'E', 'F', 'G']


#### itertools.cycle(seq)

- Make an iterator returning elements from the iterable and saving a copy of each. When the iterable is exhausted, return elements from the saved copy. Repeats indefinitely. _itertools.cycle(iterable)_

https://docs.python.org/3/library/itertools.html#itertools.cycle

In [32]:
from itertools import cycle

print(list(islice(cycle('abc'), 12)))

['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c']


In [45]:
# iterators can be used in different ways
lst = ['advanced','python','for','data','science']
print(list(islice(cycle(lst), 10)))

['advanced', 'python', 'for', 'data', 'science', 'advanced', 'python', 'for', 'data', 'science']


#### itertools.repeat(elem [,times])

- Make an iterator that returns object over and over again. Runs indefinitely unless the times argument is specified.

_itertools.repeat(object[, times])

 
https://docs.python.org/3/library/itertools.html#itertools.repeat

In [30]:
from itertools import repeat

# repeat an object: e.g. string

print(list(repeat('abcde', 5)))

['abcde', 'abcde', 'abcde', 'abcde', 'abcde']


In [30]:
# repeat an object: e.g. list
print(list(repeat(['CDS', 'Courant', 'NYU'], 5)))


[['CDS', 'Courant', 'NYU'], ['CDS', 'Courant', 'NYU'], ['CDS', 'Courant', 'NYU'], ['CDS', 'Courant', 'NYU'], ['CDS', 'Courant', 'NYU']]


## Finite Iterators

- Learn about a range of finite iterators provided by itertools.
- Most of the iterators that you create with itertools are not infinite.
-  In this sections, we will be studying the finite iterators of itertools.
-   To get output that is readable, we will be using Python’s built-in list type.
-   If you do not use list, then you will only get an itertools object printed out.



itertools also has a number of iterators that terminate.

#### itertools.accumulate(seq [, func])

- Make an iterator that returns accumulated sums, or accumulated results of other binary functions (specified via the optional func argument).

_itertools.accumulate(iterable[, func, *, initial=None])

- The default of accumulate is addition, so let’s give that a quick try:

https://docs.python.org/3/library/itertools.html#itertools.repeat

In [ ]:
from itertools import accumulate

# 1, 1 + 2, 1 + 2 + 3, 1 + 2 + 3 + 4,...

print(list(accumulate(range(1, 11))))

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]


 Here we import accumulate and pass it a range of 10 numbers. 
 
 It adds each of them in turn, so the first is 1, the second is 1 + 2, the third is 1 + 2+3 , etc. 
 
 Now let’s import the operator module and add it into the mix:

In [ ]:
import operator

# 1, 1 * 2, 1 * 2 * 3, 1 * 2 * 3 * 4

print(list(accumulate(range(1, 11), operator.mul)))

[1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800]



Here we pass the range 1 through 11 to our accumulate iterator. 

We also pass it a function operator.mul. 

This function accepts to arguments to be multiplied.

So for each iteration, it multiplies instead of adds (1 × 1 = 1, 1 × 2 = 2, 2 × 3 = 6, etc).

In [51]:
# it can also handle non-numeric lists such as strings

print(list(accumulate('cds_nyu')))

print(list(accumulate(repeat('python ', 3))))

['c', 'cd', 'cds', 'cds_', 'cds_n', 'cds_ny', 'cds_nyu']
['python ', 'python python ', 'python python python ']


More examples here: https://docs.python.org/3/library/itertools.html#itertools.accumulate

shows some other interesting examples such as the amortization of a loan or the chaotic recurrence relation.

You should definitely give those examples a look as they are will worth your time.

#### itertools.chain(*iterables) 

- Make an iterator that returns elements from the first iterable until it is exhausted, then proceeds to the next iterable, until all of the iterables are exhausted.
- Used for treating consecutive sequences as a single sequence.

https://docs.python.org/3/library/itertools.html#itertools.repeat

For example, suppose we have a list with some items already in it and two other lists that we wanted to add to the original list, but we only wanted to add the items in each list. 

**`itertools.chain()` is simply the iterator version of the `extend()` method of the Python list!**

You might try something like this:

In [32]:
my_list = ['foo', 'bar']
cmd = ['ls', '/some/dir']
numbers = list(range(5))
my_list.extend(cmd)
my_list.extend(numbers)

print(my_list)

['foo', 'bar', 'ls', '/some/dir', 0, 1, 2, 3, 4]


Well that didn’t work quite the way we wanted it to.
--> actually it did work correctly, but it's less elegant becauase 1) we had to call `extend()` twice, and 2) we had to manually modify `my_list`.

The itertools module provides a much more elegant way of flattening these lists into one:

The chain iterator takes a series of iterables and flattens them down into one long iterable.

In [33]:
from itertools import chain

my_list = list(chain(['foo', 'bar'], cmd, numbers))

print(my_list)

['foo', 'bar', 'ls', '/some/dir', 0, 1, 2, 3, 4]


In [34]:
my_list = list(chain('foo', 'bar'))

print(my_list)

['f', 'o', 'o', 'b', 'a', 'r']


Both of these methods are certainly valid, but using chain is a more efficient if the iterator is being used in a loop rather than simply converting to a list.

#### itertools.compress(seq, selectors)
Useful for filtering an iterable using a second boolean iterable (i.e. an indicator)

- Make an iterator that filters elements from data returning only those that have a corresponding element in selectors that evaluates to True.

- Stops when either the data or selectors iterables has been exhausted.

https://docs.python.org/3/library/itertools.html#itertools.compress

Let’s take a look:


In [36]:
from itertools import compress

letters = 'ABCDEFGHIJKJM'
bools = [True, True, False, True, False, True, True, True, False, True]
print(len(letters), len(bools))

# notice the sizes do not need to match
print(list(compress(letters, bools)))

13 10
['A', 'B', 'D', 'F', 'G', 'H', 'J']


In this example, we have a group of letters and a list of five Booleans which are passed to the compress iterable. 

compress will go through each iterable argument and check the first against the second. 

If the second has a matching True, then it will be kept. If it’s a False, then that item will be dropped.

In [8]:
def either_aeiou(e):
#     return (e == 'A') or (e == 'E') or (e == 'I') or (e == 'O') or (e == 'U')
    return e in 'AEIOU'

print(list(compress(letters, [either_aeiou(e) for e in letters])))

['A', 'E', 'I']


---

### itertools.dropwhile(predicate, seq)  

There is a neat little iterator contained in itertools called dropwhile. 

This fun little iterator will drop elements as long as the filter criteria is True. Because of this, you will not see any output from this iterator until the predicate becomes False. This can make the start-up time lengthy, so it’s something to be aware of: 


- Drop the elements while the predicate is True; afterwards, returns every element.

- Make an iterator that drops elements from the iterable as long as the predicate is true; afterwards, returns every element. 

- Note, the iterator does not produce any output until the predicate first becomes false, so it may have a lengthy start-up time. 

https://docs.python.org/3/library/itertools.html#itertools.compress

### itertools.takewhile(predicate, seq)  

- Take the elements while the predicate is True

- Make an iterator that returns elements from the iterable as long as the predicate is true.

https://docs.python.org/3/library/itertools.html#itertools.compress

In [11]:
from itertools import dropwhile, takewhile

print(list(dropwhile(lambda x: x > 5, [6, 7, 8, 9, 10, 1, 2, 3, 20, 21,22])))

print(list(takewhile(lambda x: x > 5, [6, 7, 8, 9, 10, 1, 2, 3, 20, 21,22])))

[1, 2, 3, 20, 21, 22]
[6, 7, 8, 9, 10]



Here we import dropwhile and then we pass it a simple function, use a lambda fuction. 

The lambda function is our predicate or filter. If the values we pass to it are True, then they will get dropped. 

Once we reach the number 5, the function returns False and we retain the number 5 and all the values that follow it.

In [12]:
lst = ['parrot', 'pelican', 'lion', 'cat', 'panther', 'dolphin', 'dog']

print("lst_take_while:", list(takewhile(lambda word: word[0] == 'p', lst)))

print("lst_drop_while:", list(dropwhile(lambda word: word[0] == 'p', lst)))


lst_take_while: ['parrot', 'pelican']
lst_drop_while: ['lion', 'cat', 'panther', 'dolphin', 'dog']


#### itertools.filterfalse(predicate, seq) 

The filterfalse function is very similar to dropwhile.

However instead of dropping values that match True, filterfalse will only return those values that evaluate to False. 
https://docs.python.org/3/library/itertools.html#itertools.ifilterfalse

Filter elements to keep only those for which the predicate is False (opposite behavior of `filter`).

Let’s use our function from the previous section to illustrate:



In [13]:
from itertools import filterfalse

# filter *all* elements for which the predicate is false

print(list(filterfalse(lambda x: x < 5, [6, 7, 8, 9, 10, 1, 2, 3, 20])))

[6, 7, 8, 9, 10, 20]


Here we pass filterfalse our function and a list of integers. 
If the integer is less than 5, it is kept. Otherwise it is thrown away.

You will notice that our result is 6, 7, 8, 9, 10 and 20. Unlike dropwhile, filterfalse will check each and every value against our predicate.

In [70]:
# contrast with the standard function filter
list(filter(lambda x: x < 5, [6, 7, 8, 9, 10, 1, 2, 3, 20]))

[1, 2, 3]

#### itertools.groupby(seq, key=None)  

The groupby iterator will return consecutive keys and groups from your iterable.

`key` is a function computing a key value for each element.

If not specified or is None, key defaults to an identity function and returns the element unchanged.

Generally, the iterable needs to already be sorted on the same key function.

https://docs.python.org/3/library/itertools.html#itertools.groupby 

This one is kind of hard to wrap your head around without seeing an example. So let’s take a look at one!

In [ ]:
from itertools import groupby

numbers = range(20)
# to group consecutive numbers from range(20) by the same **quotient** when divided by 5;
# i.e. for x in range(20) group by x // 5

for (key, group) in groupby(numbers, lambda x: x // 5):
    print(key, list(group))

0 [0, 1, 2, 3, 4]
1 [5, 6, 7, 8, 9]
2 [10, 11, 12, 13, 14]
3 [15, 16, 17, 18, 19]


In [ ]:
import random

from itertools import groupby

numbers = list(range(20))
random.shuffle(numbers) #
# to group consecutive numbers from range(20) by the same **quotient** when divided by 5;
# i.e. for x in range(20) group by x // 5

for (key, group) in groupby(numbers, lambda x: x // 5):
    print(key, list(group))

1 [5]
0 [0]
2 [14]
3 [19]
1 [6, 9]
0 [2]
2 [11]
3 [15]
2 [13]
3 [17]
1 [8]
2 [12]
0 [1, 4]
3 [18]
2 [10]
3 [16]
1 [7]
0 [3]


Randomizes the order of the list, which makes groupby behave very differently .

Only groups consecutive elements with the same key.

It does NOT collect all items with the same key globally.

In [ ]:
# group the list of elements by the same **remainder**
for (key, group) in groupby(numbers, lambda x: x % 5):
    print(key, list(group))

4 [19]
3 [18]
0 [10]
1 [6]
3 [13]
1 [1]
4 [9]
0 [15]
2 [7]
4 [14]
0 [5]
1 [16, 11]
3 [8]
4 [4]
3 [3]
2 [2, 17, 12]
0 [0]


In [45]:
# combining the groups with same key
import collections
groups = collections.defaultdict(list)

for (key, group) in groupby(numbers, lambda x: x % 5):
    groups[key] += group

for key, group in groups.items():
    print(key, group)

4 [19, 9, 14, 4]
3 [18, 13, 8, 3]
0 [10, 15, 5, 0]
1 [6, 1, 16, 11]
2 [7, 2, 17, 12]


In [46]:
keyfn = lambda x: x % 5

for (key, group) in groupby(sorted(numbers, key=keyfn), keyfn):
    print(key, list(group))

0 [10, 15, 5, 0]
1 [6, 1, 16, 11]
2 [7, 2, 17, 12]
3 [18, 13, 8, 3]
4 [19, 9, 14, 4]



The groupby iterator groups values based on a key. The key argument is a function, or if none is specified, defaults to the identity function which returns the element unchanged. 

In this case, we provide a function that returns the first element of the tuple, which is what we want to use for the key. 

A new group is generated every time the value of the key function changes (which is why it is necessary to sort the data.)

#### itertools.starmap(function, seq)

The starmap iterator computes using the function and iterable provided as arguments. 


https://docs.python.org/3/library/itertools.html#itertools.starmap

Iterator that computes the function using arguments obtained from the iterable. 


- Used instead of map() when argument parameters are already grouped in tuples from a single iterable (when the data has been “pre-zipped”).

- The difference between map() and starmap() parallels the distinction between function(a,b) and function(*c).

In other words, the function provided as an argument to starmap can iteself take a variable number of arguments.

In [47]:
from itertools import starmap

# here is the iterable: [(1,2), (3,4), (5,6)]

for item in starmap(lambda u, v: u + v, [(1, 2), (3, 4), (5, 6)]):
    print(item)

3
7
11



Here we create a simple adding function that accepts two arguments. 

Next we create a for loop and call starmap with the function as its first argument and a list of tuples for the iterable. 

The starmap function will then pass each tuple element into the function and return an iterator of the results, which we print out.

In [48]:
def add(u, v, w):
    return u + v + w

for item in starmap(add, [(1, 2, 3), (3, 4, 5), (5, 6, 7)]):
    print(item)

6
12
18


#### itertools.tee(seq, n=2)

The tee iterator creates n iterators from a single iterable. 
What this means is that you can create multiple iterators from one iterable. 
- Creates n iterators from the given sequence

Let’s look at some explanatory code to how it works:

In [49]:
from itertools import tee
data = 'ABCDE'
iters = tee(data, 5)

for i in range(5):
    print(f'iterator:{i}')
    for item in iters[i]:
        print(item, end="")
    print("\n")

iterator:0
ABCDE

iterator:1
ABCDE

iterator:2
ABCDE

iterator:3
ABCDE

iterator:4
ABCDE



Here we create a 5-letter string and pass it to tee. 

Because tee defaults to 2, we use multiple assignment to acquire the two iterators that are returned from tee. 

Finally we loop over each of the iterators and print out their contents. As you can see, their content are the same.

#### itertools.zip_longest(*seq, fillvalue=None)  

The zip_longest iterator can be used to zip two iterables together. 

If the iterables don’t happen to be the same length, then you can also pass in a fillvalue. 

https://docs.python.org/3/library/itertools.html#itertools.izip_longest  

- An iterator that aggregates elements from each of the iterables. 

Let’s look at a silly example based on the documentation for this function:


In [14]:
# The standard zip stops after the shortest list is finished
list(zip('AB', 'xyzw', range(5)))

[('A', 'x', 0), ('B', 'y', 1)]


- In this code we import zip_longest and then pass it two strings to zip together.

-  You will note that the first string is 2-characters long while the second is 4-characters in length.

-   When we loop over this and print it out, you will see that we get tuples returned.

-   The first two tuples are combinations of the first and second letters from each string respectively.

-   zip stops after the shortest list is finished

In [50]:
from itertools import zip_longest

print(list(zip_longest('AB', 'xyzw', fillvalue='_')))

[('A', 'x'), ('B', 'y'), ('_', 'z'), ('_', 'w')]


In [101]:
print(list(zip_longest('AB', 'xyzw', range(5), fillvalue='_')))

[('A', 'x', 0), ('B', 'y', 1), ('_', 'z', 2), ('_', 'w', 3), ('_', '_', 4)]


In [102]:
# useful to create dictionaries

vals = ['pqr', 'uvw', 'xyz']

dc = dict(zip_longest('1234567', vals, fillvalue='blank_value'))
print("dict:", dc)

dict: {'1': 'pqr', '2': 'uvw', '3': 'xyz', '4': 'blank_value', '5': 'blank_value', '6': 'blank_value', '7': 'blank_value'}


## Combinatoric Generators
Iterators that can be used for creating combinations and permutations of data

- The _itertools_ library contains four iterators that can be used for creating combinations and permutations of data.
- We will be covering these fun iterators in this section.

#### itertools.combinations(seq, r) 

- If you have the need to create combinations, Python has you covered with _itertools.combinations_. What _combinations_ allows you to do is create an iterator that generates combinations of length ‘r’ from an iterable.

#### itertools.combinations_with_replacement(seq, r)

- The _combinations_with_replacement_ iterator is very similar to combinations. The only difference is that it will create combinations where elements do repeat. 


#### itertools.permutations(iterable, r=None)

- The _permutations_ sub-module of _itertools_ will return successive _r_ length permutations of elements from the iterable you give it. Much like the _combinations_ function, _permutations_ are emitted in lexicographic sort order. 


#### itertools.product(*iterables, repeat=1)

- The _itertools_ package has a neat little function for creating Cartesian products from a series of input iterables. Yes, that function is _product_. https://en.wikipedia.org/wiki/Cartesian_product

---

E.g. There is an urn with four balls: yellow, green, red, and blue.  

Q: In how many ways can one pick two (three) balls without replacement?  

Q: In how many ways can one pick two (three) balls with replacement?

If you have the need to create combinations, Python has you covered with itertools.combinations.
What combinations allows you to do is create an iterator that generates combinations of length ‘r’ from an iterable.
Let’s take a look:

In [105]:
from itertools import combinations
# Cr = n!/r!(n-r)!, n =4, r =2
for item in combinations('RBGY', 2):
    print(''.join(item), end="; ")

RB; RG; RY; BG; BY; GY; 

Also worth noting is that combinations will not produce repeat values in the combinations if all the input elements are unique.

- The combinations_with_replacement iterator is very similar to combinations.
- The only difference is that it will create combinations where elements do repeat.
-  Let’s try an example from the previous section to illustrate:

In [106]:
from itertools import combinations_with_replacement

for item in combinations_with_replacement('RBGY', 2):
    print(''.join(item), end="; ")

RR; RB; RG; RY; BB; BG; BY; GG; GY; YY; 

- The permutations sub-module of itertools will return successive r length permutations of elements from the iterable you give it.
- Much like the combinations function, permutations are emitted in lexicographic sort order. 
- Let’s take a look:

In [ ]:
from itertools import permutations

# pr  =n!/(n-r)! N= 4, r =2

for item in permutations('RBGY', 2):
    print(''.join(item), end="; ")

RB; RG; RY; BR; BG; BY; GR; GB; GY; YR; YB; YG; 

#### itertools.product(*seq, repeat=1)

The itertools package has a neat little function for creating Cartesian products from a series of input iterables.
Yes, that function is product. 

- Produces the **cartesian product** of sequences


In [25]:
from itertools import product

arrays = [('A', 'B'), ('a', 'b', 'c')]
cart_prod = list(product(*arrays))
print(cart_prod)

# size (cardinality) is 2 * 3  = 6


[('A', 'a'), ('A', 'b'), ('A', 'c'), ('B', 'a'), ('B', 'b'), ('B', 'c')]


Here we import product and then set up a list of tuples which we assign to the variable arrays.
Next we call product with those arrays. 
- Notice that we call it using *arrays.

In [ ]:

# Calling a function with all possible choices of parameters

choices = [(-1,1), (-3,3), (-5,5)]
cp = list(product(*choices))
print(cp)

def f(a, b, c):
    print('(', a, b, c, ')')

for args in cp:
    f(*args)

[(-1, -3, -5), (-1, -3, 5), (-1, 3, -5), (-1, 3, 5), (1, -3, -5), (1, -3, 5), (1, 3, -5), (1, 3, 5)]
( -1 -3 -5 )
( -1 -3 5 )
( -1 3 -5 )
( -1 3 5 )
( 1 -3 -5 )
( 1 -3 5 )
( 1 3 -5 )
( 1 3 5 )


The syntax *args can also be used when calling a function. 

This will cause the arguments to be “exploded” or applied to the function in sequence.

- kwargs in Python is a special syntax that allows you to pass a keyworded, variable-length argument dictionary to a function. 
-  It is short for "keyword arguments".

In [ ]:
choices = {
    'a': [-1, 1],
    'b': [-3, 3],
    'c': [-5, 5],
}

#kwargs in Python is a special syntax that allows you to pass a keyworded, variable-length argument dictionary to a function.
# It is short for "keyword arguments".

def f(**kwargs):
    print(kwargs)

all_dicts = list(dict(zip(choices.keys(), vals)) for vals in product(*choices.values()))
for d in all_dicts:
    f(**d)

{'a': -1, 'b': -3, 'c': -5}
{'a': -1, 'b': -3, 'c': 5}
{'a': -1, 'b': 3, 'c': -5}
{'a': -1, 'b': 3, 'c': 5}
{'a': 1, 'b': -3, 'c': -5}
{'a': 1, 'b': -3, 'c': 5}
{'a': 1, 'b': 3, 'c': -5}
{'a': 1, 'b': 3, 'c': 5}


In [ ]:
def f(**kwargs):
    print(kwargs)

def g(kwargs):
    print(kwargs)

def h(*args):
    print(args)

f(a=1, b=2, c=3)
f(**{'a' : 1, 'b' : 2, 'c' : 3})

#g(a=1, b=2, c=3)

h(*{'a' : 1, 'b' : 2, 'c' : 3})

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3}
('a', 'b', 'c')


In [155]:
import numpy as np

M = np.zeros((2, 2))
cids = product((0, 1), (0, 1))

print("cids:", cids)

for i, e in enumerate(cids):
    M[e] = i * 100
    print("i = %s, e = %s" % (i, e))

print("\nM=\n", M)

cids: <itertools.product object at 0x7fda88432e00>
i = 0, e = (0, 0)
i = 1, e = (0, 1)
i = 2, e = (1, 0)
i = 3, e = (1, 1)

M=
 [[  0. 100.]
 [200. 300.]]


In [156]:
import numpy as np

M = np.zeros((3, 3, 3))
cids = product((0,1,2), (0,1,2), (0,1,2))


print("cids: ", cids)

for i, e  in enumerate(cids):
    M[e] = i * 100
    print(f"i = {i:>2}, e = {e}")

print("\nM=\n", M)

cids:  <itertools.product object at 0x7fda88436ac0>
i =  0, e = (0, 0, 0)
i =  1, e = (0, 0, 1)
i =  2, e = (0, 0, 2)
i =  3, e = (0, 1, 0)
i =  4, e = (0, 1, 1)
i =  5, e = (0, 1, 2)
i =  6, e = (0, 2, 0)
i =  7, e = (0, 2, 1)
i =  8, e = (0, 2, 2)
i =  9, e = (1, 0, 0)
i = 10, e = (1, 0, 1)
i = 11, e = (1, 0, 2)
i = 12, e = (1, 1, 0)
i = 13, e = (1, 1, 1)
i = 14, e = (1, 1, 2)
i = 15, e = (1, 2, 0)
i = 16, e = (1, 2, 1)
i = 17, e = (1, 2, 2)
i = 18, e = (2, 0, 0)
i = 19, e = (2, 0, 1)
i = 20, e = (2, 0, 2)
i = 21, e = (2, 1, 0)
i = 22, e = (2, 1, 1)
i = 23, e = (2, 1, 2)
i = 24, e = (2, 2, 0)
i = 25, e = (2, 2, 1)
i = 26, e = (2, 2, 2)

M=
 [[[   0.  100.  200.]
  [ 300.  400.  500.]
  [ 600.  700.  800.]]

 [[ 900. 1000. 1100.]
  [1200. 1300. 1400.]
  [1500. 1600. 1700.]]

 [[1800. 1900. 2000.]
  [2100. 2200. 2300.]
  [2400. 2500. 2600.]]]
